apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuca-custom-deployment.fullname" . }}
  labels:
    {{- include "neuca-custom-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ports }}
  ports:
    {{- toYaml .Values.service.ports | nindent 2 }}
  {{- end }}
  selector:
    {{- include "neuca-custom-deployment.selectorLabels" . | nindent 4 }}
