apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-pod.fullname" . }}
  labels:
    {{- include "custom-pod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ports }}
  ports:
    {{- toYaml .Values.service.ports | nindent 2 }}
  {{- end }}
  selector:
    {{- include "custom-pod.selectorLabels" . | nindent 4 }}
