apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-startup-script
data:
  startup.sh: |
  {{- if .Values.global.vllm }}
    {{- .Values.vllmStartupScript | nindent 4 }}
  {{- else }}
    {{- .Values.customStartupScript | nindent 4 }}
  {{- end }}
