apiVersion: v1
kind: Secret
metadata:
  name: hpe-user-secret-{{ regexReplaceAll "\\." .Values.edf.clusterName "-" }}
  namespace:  {{ .Release.Namespace}}
type: Opaque
data:
{{- if .Values.edf.PasswordAuthentication }}
  MAPR_CLUSTER_PASSWORD: {{ .Values.edf.password |  b64enc | quote }}
  MAPR_CLUSTER_USER: {{ .Values.edf.admin |  b64enc | quote }}
{{ else }}
  MAPR_CLUSTER_TICKET: {{ .Values.edf.ticket |  b64enc | quote }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: hpe-ticket-secret-{{ regexReplaceAll "\\." .Values.edf.clusterName "-" }}
  namespace:  {{ .Release.Namespace}}
type: Opaque
data:
  CONTAINER_TICKET: {{ .Values.edf.ticket |  b64enc | quote }}
