# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

airgap:
  enabled: false
  registry: ""
clusterName: ""

edf:
  ticket: ""
  admin: "mapr"
  password: ""
  clusterName: ""
  cldbHosts: ""
  restServers: ""
  PasswordAuthentication: false
  defaultStorageClass: true
